version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # due to https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/issues/68
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        versions: ["3.5.4", "3.5.5"]
    groups:
      maven-dependencies:
        patterns:
          - "*"


  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "ci"
